source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ResearchGA' do
    #Old-style: SDK
    pod 'GoogleAnalytics', '3.12.0'
    #New-style
    pod 'Google/Analytics'
end




